import { ResumeSheet } from '@/components/ResumeSheet';
import loadPageContent from '@/utils/loadPageContent';
import Head from 'next/head';

import { Lato } from '@next/font/google';
const fontLato = Lato({ weight: ['400', '700', '900'], subsets: ['latin'] });

type IndexProps = Awaited<ReturnType<typeof getStaticProps>>['props'];

export default function Index(data: IndexProps) {
  return (
    <>
      <Head>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <div className={'desk ' + fontLato.className}>
        <ResumeSheet {...data} />
        <footer className='footer'>
          <div className='text-center'>
            <small className='copyright'>{data.home.frontmatter.copyright}</small>
          </div>
        </footer>
      </div>
    </>
  );
}

export async function getStaticProps() {
  return { props: await loadPageContent() };
}
