import Head from 'next/head';

import { TheMain } from './components/TheMain';
import { TheSidebar } from './components/TheSidebar';
import { TheFooter } from './components/TheFooter';

// import { Roboto, New_Rocker } from '@next/font/google';
// const fontRoboto = Roboto({ weight: ['400', '500', '700', '900'] });
// const fontNewRocker = New_Rocker({ weight: ['400'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Stefan Ginev — CV</title>

        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />

        <link
          href='https://fonts.googleapis.com/css?family=Roboto:400,500,400italic,300italic,300,500italic,700,700italic,900,900italic'
          rel='stylesheet'
          type='text/css'
        />
        <script
          defer
          src='https://use.fontawesome.com/releases/v5.1.0/js/all.js'
          integrity='sha384-3LK/3kTpDE/Pkp8gTNp2gR/2gOiwQ6QaO7Td0zV76UFJVhqLl4Vl3KL1We6q6wR9'
        ></script>
      </Head>

      <main className='wrapper'>
        <TheSidebar />
        <TheMain />
      </main>

      <TheFooter />
    </>
  );
}
